### ISSUE TITLE
Completion script generation broken with Mordant 3.0

### ISSUE THREAD

**Issue by sschuberth** [ajalt/mordant#230]
In our upgrade to Mordant 3.0 we [get](https://github.com/oss-review-toolkit/ort/actions/runs/10762258411/job/29842371327#step:4:23)

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void com.github.ajalt.mordant.terminal.Terminal.<init>(com.github.ajalt.mordant.rendering.AnsiLevel, com.github.ajalt.mordant.rendering.Theme, java.lang.Integer, java.lang.Integer, java.lang.Boolean, int, java.lang.Boolean, int, kotlin.jvm.internal.DefaultConstructorMarker)'
        at com.github.ajalt.clikt.core.Context$Builder.<init>(Context.kt:266)
        at com.github.ajalt.clikt.core.Context$Companion.build$clikt(Context.kt:351)
        at com.github.ajalt.clikt.core.CliktCommand.createContext(CliktCommand.kt:140)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:455)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:454)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:474)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:481)
        at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:85)
```

when running

    cli/build/install/ort/bin/ort --generate-completion=bash

**Comment by ajalt** [comment]
That's expected; Mordant 3.0 is not backwards compatible (as indicated by the major version bump). I'll release a new version of clikt soon.
