### ISSUE TITLE
Animation issue

### ISSUE THREAD

**Issue by elect86** [ajalt/mordant#34]
Hello AJ,

nice to see this project is rocking!

Anyway, I quickly tried the animation sample and after a few seconds I get:
```kotlin
Exception in thread "Thread-0" java.lang.IllegalStateException: Shutdown in progress
	at java.base/java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.base/java.lang.Runtime.removeShutdownHook(Runtime.java:244)
	at com.github.ajalt.mordant.internal.JvmTerminalCursor.show(MppImpl.kt:92)
	at com.github.ajalt.mordant.internal.JvmTerminalCursor.hide$lambda-3$lambda-2(MppImpl.kt:102)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Also, I noticed I have to use `mordant-jvm` also on kotlin scripts, you may want to add that to the readme

**Comment by ajalt** [comment]
Can you share more information on how you're running the sample? What JDK are you using?
