### ISSUE TITLE
Using colormath in conjunction with mordant (?)

### ISSUE THREAD

**Issue by RaphaelTarita** [ajalt/mordant#51]
I'm currently struggling a bit to use some functionality of the colormath library in a project together with mordant. From the buildscripts it seems that mordant does not directly depend on colormath, but includes its API for interoperability. This leads me to believe that using mordant and colormath in conjunction _a thing_.

Since mordant only depends on the API, it does not pull in the colormath package, which means that I have to include it myself in my buildscript to use functionality from there. When I do that, though, I get `java.lang.NoClassDefFoundError`s for various colormath classes at runtime (`RGB` for example).

For example:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/ajalt/colormath/RGB
	at com.github.ajalt.mordant.rendering.Theme.<clinit>(Theme.kt:13)
	at com.github.ajalt.mordant.terminal.Terminal.<init>(Terminal.kt:24)
	at [my code]
Caused by: java.lang.ClassNotFoundException: com.github.ajalt.colormath.RGB
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```

I am therefore not entirely sure whether I am doing something wrong. Maybe the versions don't match? 

In any case I'd be thankful for some insight as to how using colormath and mordant together is done correctly.

Thanks!

Version Data:

Kotlin/JVM 1.6.10 (JVM target 17, also tested with 11)
mordant 2.0.0-beta2
colormath 3.2.0
OpenJDK 17.0.2-8
Gradle 7.3
Operating System: Windows 11 Pro x86_64

**Comment by RaphaelTarita** [comment]
I analyzed this further, and it seems as if `com.github.ajalt.mordant.rendering.Theme` uses the import `com.github.ajalt.colormath.RGB`, but (atleast in recent versions) the class is located in `com.github.ajalt.colormath.model.RGB`. Could this be the problem?

Also it seems that this issue does no longer occur in the `2.0.0-beta4` version of mordant
